# Use new container infrastructure to enable caching
sudo: true

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  # sdl2
  - curl https://www.libsdl.org/release/SDL2-2.0.5.tar.gz -o SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - (cd SDL2-2.0.5 && ./configure && make && sudo make install)
  - sudo ldconfig

install:
  # Build dependencies
  - stack --no-terminal --install-ghc build --only-dependencies

script:
  - stack --no-terminal build --haddock --no-haddock-deps
