name:                purple-muon
synopsis:            A multiplayer space game
description:         Please see README.md
build-type:          Custom
license:             GPL-3
license-file:        LICENSE
author:              Robin Raymond
maintainer:          robin@robinraymond.de
copyright:           2016-2017 Robin Raymond
category:            Games
extra-source-files:  README.md
github:              r-raymond/purple-muon

ghc-options: -Wall

data-files:
    - res/png/*
    - res/png/gameicons/*
    - res/png/gameicons_extended/*
    - res/wav/*

default-extensions:
    - OverloadedStrings
    - NoImplicitPrelude
    - GeneralizedNewtypeDeriving
    - DeriveGeneric
    - FlexibleContexts

dependencies:
    - base >= 4.7 && < 5
    - binary
    - bytestring
    - containers
    - digest
    - errors
    - fast-logger
    - formatting
    - JuicyPixels
    - lens
    - linear
    - mtl
    - network
    - protolude
    - sdl2
    - sdl2-mixer
    - sdl2-ttf
    - stm
    - thyme
    - vector
    - optparse-applicative
    - vector-space
    - xml
    - zlib

library:
  source-dirs: src
  exposed-modules:
    - Version
    - PurpleMuon.Network.Types
    - PurpleMuon.Network.Message
    - PurpleMuon.Network.Util
    - PurpleMuon.Physics.Types
    - PurpleMuon.Physics.Algorithm
    - PurpleMuon.Physics.Constants
    - PurpleMuon.Util.MonadError

    - Client.Event
    - Client.Frames
    - Client.Image
    - Client.Init
    - Client.MainLoop
    - Client.Types
    - Client.Video.Texture
    - Client.Video.Types
    - Client.Main

    - Server.Main

executables:
    pm-client:
        source-dirs: client
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - purple-muon

    pm-server:
        source-dirs: server
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - purple-muon
