name:                purple-muon
synopsis:            A multiplayer space game
description:         Please see README.md
license:             GPL-3
license-file:        LICENSE
author:              Robin Raymond
maintainer:          robin@robinraymond.de
copyright:           2016 Robin Raymond
category:            Games
build-type:          Simple
extra-source-files:  README.md
github:              r-raymond/purple-muon

ghc-options: -Wall -O -Werror

default-extensions:
    - OverloadedStrings
    - NoImplicitPrelude
    - GeneralizedNewtypeDeriving
    - DeriveGeneric

dependencies:
    - base >= 4.7 && < 5
    - protolude
    - bytestring
    - network
    - linear
    - lens
    - containers
    - vector-space
    - sdl2
    - thyme
    - formatting
    - xml
    - JuicyPixels

library:
  source-dirs: common
  exposed-modules:
    - PurpleMuon.Network.Types
    - PurpleMuon.Network.Message
    - PurpleMuon.Network.Util
    - PurpleMuon.Physics.Types
    - PurpleMuon.Physics.Algorithm
    - PurpleMuon.Physics.Constants

executables:
    pm-client:
        source-dirs: client
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        other-modules:
            - Client.Types
            - Client.Event
            - Client.Init
            - Client.MainLoop
            - Client.Frames
            - Client.Image
        dependencies:
            - purple-muon

    pm-server:
        source-dirs: server
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - purple-muon
