name:                purple-muon
synopsis:            A multiplayer space game
description:         Please see README.md
build-type:          Custom
license:             GPL-3
license-file:        LICENSE
author:              Robin Raymond
maintainer:          robin@robinraymond.de
copyright:           2016-2017 Robin Raymond
category:            Games
extra-source-files:  README.md
github:              r-raymond/purple-muon

ghc-options: -Wall

data-files:
    - res/png/*
    - res/png/gameicons/*
    - res/png/gameicons_extended/*
    - res/ogg/*
    - res/fonts/*
    - res/fonts/fyodor/truetype/*

default-extensions:
    - DeriveGeneric
    - FlexibleContexts
    - GeneralizedNewtypeDeriving
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - OverloadedStrings
    - ScopedTypeVariables
    - TypeFamilies

dependencies:
    - base >= 4.7 && < 5
    - binary
    - bytestring
    - containers
    - digest
    - errors
    - fast-logger
    - filepath
    - formatting
    - hashtables
    - lens
    - linear
    - mtl
    - network
    - optparse-applicative
    - protolude
    - sdl2
    - sdl2-image
    - sdl2-mixer
    - sdl2-ttf
    - stm
    - thyme
    - vector
    - vector-space
    - xml
    - zlib

library:
  source-dirs: src
  other-modules:
    - Paths_purple_muon
    - Version

executables:
    pm-client:
        source-dirs: client
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - purple-muon

    pm-server:
        source-dirs: server
        main: Main.hs
        ghc-options: -threaded -rtsopts -with-rtsopts=-N
        dependencies:
            - purple-muon
